### ISSUE TITLE
List of supported document tags

### ISSUE THREAD

**Issue by drbenschmidt** [Geaz/sharpDox#25]
Hello,

I just had sharpDox create some pretty slick docs for a new project I'm working on, but I'm wondering if there is a list of supported XML comment tags anywhere. I noticed a few tags either didn't get pulled in when generating the docs or they didn't get exported when generating the HTML.

Microsoft recommends using these: http://msdn.microsoft.com/en-us/library/5ast78ax.aspx

It would also be awesome to support the `<inheritdoc />` tag that other doc gen applications use.

PS, awesome project so far!

**Comment by Geaz** [comment]
Fixed in the latest release.

**Comment by mzdunek** [comment]
Doesnt work for me, throws error in DocumentationParser line 36.

**Comment by Geaz** [comment]
Could you give me an example how you are using the tag? Thank you!

**Comment by mzdunek** [comment]
example

```
using System;

namespace console03.Test1
{
	/// <summary>
	/// Description of ITest1.
	/// </summary>
	public interface ITest1
	{
		/// <summary>
		/// Description of Method1
		/// </summary>
		void Method1();
	}
}
```
```
using System;

namespace console03.Test1.Impl
{
	/// <inheritdoc />
	public class Test1 : ITest1
	{
		#region ITest1 implementation

		/// <inheritdoc />
		public void Method1()
		{
			throw new NotImplementedException();
		}

		#endregion
	}
}
```

[example project](http://www.load.to/ropj912r5A/console03.7z)

**Comment by Geaz** [comment]
Thank you! The problem seems to be, that the <inheritdoc /> is just allowed on member level at the moment. If you remove the tag from your class, it should work. Will look into this problem.

**Comment by mzdunek** [comment]
I removed tags from classes, now it works fine. Thanks.
