### ISSUE TITLE
Can't generate documentation in an automated way

### ISSUE THREAD

**Issue by craftworkgames** [Geaz/sharpDox#28]
The whole point of having a Console shell is so that you can generate documentation automatically from a build system.

Currently running SharpDox from the command line prompts the user to choose either Console or GUI. This is stupid, it defeats the purpose of having a console application in the first place. A console application should never block execution by asking for user input. As soon as it does, it will halt any automated scripts or build systems and cause them to fail.

Of course, I managed to figure out a workaround by looking at the source code. Simply delete the GUI shell. But why should I have to do that?

A better option would be to provide 2 executrices. The GUI and the Console. Simple, easy to understand.

**Comment by Geaz** [comment]
Hello & thank you for the comment!

You are right, that this may not be the best way to handle different frontends. Way back I designed it this way and never rethought it. Maybe now is the time for it :)

I will do some test and come back to you at the weekend!

**Comment by craftworkgames** [comment]
No problem. Sorry if I came across a little angry. It brought my build server to it's knees and I was a little annoyed.

I'm currently in the middle of trying to get SharpDox working on a Team City build server. The documentation it produces is very good but it has some annoying bugs. 

Nice work on what you've done so far though. I'm sure with just a few more tweaks it can be very useful.

If you like, I can take a fork of the repository and make some changes for you. We can discuss them here first.

**Comment by Geaz** [comment]
Sure, go for it! I appreciate any contribution. 
Furthermore I would love to here about the bugs. Just open some more issues, if you like.

Just an information: At the moment I work on a nuget package to integrate the documentation generation into the build process of a solution automatically. So hopefully no need to do it by yourself in the future.

**Comment by Geaz** [comment]
I made huge refactorings and created two seperate executables in the dev branch.
If you want to try it, please make sure that you also take the latest build of the html plugin.
