### ISSUE TITLE
The console should NEVER block

### ISSUE THREAD

**Issue by craftworkgames** [Geaz/sharpDox#29]
Hey mate

I got the latest dev branch and took a look. Everything is building fine and it runs. However, I noticed the the following lines in `SDConsole.Start()`

            System.Console.WriteLine(_strings.PressToEnd);
            System.Console.ReadLine();

This is going to be a problem.

You see, on an automated build system when generating docs from the command line it's not okay to ask questions, even if it's just "Press enter to exit" because this will halt the build system and it won't be able to continue.

Fortunately, this is very easy to fix. Just wrap an `#if DEBUG` around it like this:

```c#
#if DEBUG
            System.Console.WriteLine(_strings.PressToEnd);
            System.Console.ReadLine();
#endif
```

This way, when you are debugging the application in Visual Studio it will continue to prompt but when you build the release version it won't.

**Comment by Geaz** [comment]
Hi,
seems like I overlooked this one. Thank for the info!
Changed, commited and closed :)
