### ISSUE TITLE
See tag is not working

### ISSUE THREAD

**Issue by digitalcosmos** [Geaz/sharpDox#35]
I tried referencing types from another file within the namespace and even types from the same file.
I would expect to be a link just like `[Type]({{"type-link:MyProject.NameSpace.ObjectType}})` but nothing happens.

I searched for your usage of `<see cref=''"/>` within the documentation of this project but it seems that it this [file](https://github.com/Geaz/sharpDox/blob/master/src/SharpDox.Model/Documentation/Token/SDToken.cs) doesn't have the `<see>` behavior reflected [here](http://doc.sharpdox.de/en/#type/SDToken?Role)

How can I provide a link to another type (preferably from another namespace that is included in the docs) in the `<summary></summary>` or `<param></param>` of a method?

Thank you for your time.

**Comment by Geaz** [comment]
In fact this is a bug in the html output. The `<see cref=''"/>` gets parsed, but the output is ignoring this token type at the moment. I include a fix in the next release (mid-June).

Thank you for your contribution!

**Comment by filoe** [comment]
Well the chm output also ignores it. This is a comparison of sandcastle and sharpdox: http://fs2.directupload.net/images/150515/tsxf84gt.png

**Comment by filoe** [comment]
Got this bug fixed?

**Comment by Geaz** [comment]
Fixed in new html exporter - will release it soon.

**Comment by filoe** [comment]
Very nice, thank you!
