### ISSUE TITLE
Configuration file shouldn't be updating when building doc

### ISSUE THREAD

**Issue by digitalcosmos** [Geaz/sharpDox#36]
The configuration file is something that is desirable to keep in source control, especially when managing multiple projects.

Upon building, this file is updated with
```
 <item key="LastBuild" value="_DATE_ - _TIME_" />
```
and source control picks up those changes on the next check-in.

I'm using Visual Studio Online and the only way to ignore this change is to get each member of the team to cloak the `.sdox' files in their projects.

In summary: Config files should only be used as input.

PS: I've noticed that the `PathToConfig` also gets updated with absolute path of the file. This is not ideal when calling the file from command line with relative path that later gets converted to absolute.

**Comment by Geaz** [comment]
Valid points. Will change these behaviors for the next release.
