### ISSUE TITLE
Console Shell exit codes

### ISSUE THREAD

**Issue by asarapas** [Geaz/sharpDox#37]
Would make sense to have exit codes returned from console shell. 
This would allow better integration to the MSBuild and other automated "runners" that need to know if Document generation succeeded or failed.

**Comment by craftworkgames** [comment]
I just wanted to say it's exciting to see activity on this project and I think these changes will make it much better.

**Comment by Geaz** [comment]
I added console exit codes for success (0) and failure (-1). If more are necessary, please open a new ticket. Thanks for the request!
