### ISSUE TITLE
Support multiple frameworks (such as NET40, NET45, WIN81, etc)

### ISSUE THREAD

**Issue by GeertvanHorrik** [Geaz/sharpDox#41]
I am considering to use this on a lot of projects that support multiple platforms (NET40, NET45, WP80, WP81, etc). What if it could create a section like MSDN does where the user can switch the target fx (some target fx don't have the same classes, although many are shared).

Then we can show that as the default on each page.

**Comment by GeertvanHorrik** [comment]
I think it is possible to create an SDTargetFramework class (we want to be dynamic, right?). Then we can put that on SDType (so we know what docs we can switch to). There are actually 2 ways to solve this problem:

```
- NET40
  - TypeA
  - TypeB
  - TypeC

- NET45 
  - TypeA
  - TypeB

etc
```

-or-

```
- TypeA
  - NET40
  - NET45
  - WP80

- TypeB
  - NET40
  - NET45
  - WP80

etc
```

For the user, the 2nd option is best (when displaying), but what do you think is best? Happy to try and PR this.

**Comment by Geaz** [comment]
May I ask you how your solution is structured, if you support different target frameworks?
Ideally there should be an own project for each target framework, right? If this is the case, it would be already possible just to create a navigation file like this:
```
-Introduction#introduction
-API
--NET40#..\src\Test40.proj
--WP8#..\src\WP8.proj
[...]
```
This way you get one navigation item for each of your target frameworks. Is this not sufficient?

**Comment by GeertvanHorrik** [comment]
We have a shared project (that contains all the source files). Then we have platform-specific target projects:

* NET40
* NET45
* NET46
* SL5
* WIN81
* WIN100
* WP80
* WP81SL
* WP81RT
* Xamarin.Android
* Xamarin.iOS

See https://github.com/catel/catel

**Comment by GeertvanHorrik** [comment]
Ideally I want something like this:

![image](https://cloud.githubusercontent.com/assets/1246444/7959661/6995db7a-09fb-11e5-9a11-a40bf132d263.png)

**Comment by Geaz** [comment]
At the moment sharpDox compiles either a single project or a whole solution, as input file or in the navigation file. So sharpDox doesn't know about different build targets at the moment. What to you thought of to make sharpDox aware of them? Scan the projects? Mapping config item (target framework <-> project file)?

**Comment by GeertvanHorrik** [comment]
Just did a quick check between different target fx (all class libraries):

* TargetFrameworkVersion
* TargetFrameworkIdentifier 
* TargetPlatformVersion 

Below is a list of known values:

* TargetFrameworkVersion => v4.0 => NET40
* TargetFrameworkVersion => v4.5 => NET45
* TargetFrameworkVersion => v4.6 => NET46
* TargetFrameworkVersion => Profile259 (something with profile) => PCL (we should probably skip this one)
* TargetFrameworkVersion => v5.0 && TargetFrameworkIdentifier => Silverlight => SL5
* TargetPlatformVersion => 8.1 => WIN81
* TargetPlatformVersion => 8.1 => WP81 (RT) (note that this is the same as WIN81, maybe check out ProjectTypeGuids
* TargetPlatformVersion => 10.0.10030.0 && TargetPlatformIdentifier => UAP => WIN100
* TargetFrameworkVersion => v8.0 && TargetFrameworkIdentifier => WindowsPhone => WP80 (Silverlight)
* TargetFrameworkVersion => v8.1 && TargetFrameworkIdentifier => WindowsPhone => WP81 (Silverlight)
* File contains "Xamarin.Android.CSharp.targets" => Xamarin.Android
* File contains "Xamarin.iOS.CSharp.targets" => Xamarin.iOS

**Comment by GeertvanHorrik** [comment]
I think we can easily create a helper method for this. The downside is that we probably need to create 1 class doc / target fx (some might overlap), but this would be a really cool feature :-)

**Comment by Geaz** [comment]
Ah, nice list :+1: 
I think it would be the best way to have a property on the SDType which indicates for which target framework the given type is available. So, go for it :-)

And thank you for your great contributions!

**Comment by GeertvanHorrik** [comment]
If I make the fx recognition and SDTargetFx, can you implement the actual html generation? That is not my strength.

**Comment by Geaz** [comment]
Sure! Just do the core work. I will update the html output afterwards.

**Comment by GeertvanHorrik** [comment]
Almost done ;-)

**Comment by GeertvanHorrik** [comment]
Closing this one, discussion can continue in the PR (see #48)
