### ISSUE TITLE
Split up the search index data from index.html

### ISSUE THREAD

**Issue by GeertvanHorrik** [geaz/sharpDox#42]
I am generating the docs for Catel, which is quite a large project. In that case the index.html is 1384 kb (26k lines). I noticed that most of this is the searchIndex data. 

What if it would be stored in searchIndex.json? That way the index.html is really fast and the search index can be loaded async.

**Comment by Geaz** [comment]
I am rewriting the html output at the moment and will take this into consideration!

**Comment by geaz** [comment]
No search available in the current html output. Will take this in consideration for a new search.
