### ISSUE TITLE
Use CommonMark

### ISSUE THREAD

**Issue by Orcomp** [Geaz/sharpDox#47]
Would you consider using CommonMark (https://github.com/Knagis/CommonMark.NET/) instead of MarkdownSharp.

One of the reasons is that it supports code highlighting out of the box, the other is that it is now becoming the standard.

**Comment by Geaz** [comment]
Thanks for the tip! Will check it out.

**Comment by Geaz** [comment]
Added in new html exporter - will release it soon.
