### ISSUE TITLE
Markdown Error - How to define code sections ?

### ISSUE THREAD

**Issue by OrkanCom** [Geaz/sharpDox#49]
Hello, this is awesome tool and we are trying to use this for our private projects. 
But we have some problems with it;

Codes are not rendering as expected. An example, here is our sharpdox code;
__________

#### 1) DOMAIN ####
- Please go to *X.Core.Domain* under ~SolutionRoot/Source/Core/ folders in your Solution Explorer.
- Create folder under this project, named "Students" and create Student.cs in it.
- Write your student information that will save to the database. Such as: FirstName, LastName, Gender, RegisterDate etc. This is your business.

using X.Core.Domain._Bases;

namespace X.Core.Domain.Students
{
    public class Student : BaseEntityWithInt, IEntity<int>
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string SchoolNumber { get; set; }
    }
}

__________

But it's rendering like;

![2015-08-28 05-25-04 ekran goruntusu](https://cloud.githubusercontent.com/assets/13241853/9537779/78e5959c-4d45-11e5-8d78-e6eec0fb97d2.png)

I'm not sure but I think; This error occours because we left too much empty spaces between code lines. I don't know. Maybe we are forgetting to put some special characters... We searched SharpDox's documentation but didn't find any usefull tips for this. Is there any special tags or characters for SharpDox to define code start and code end? An example;

#### 1) DOMAIN ####
- Please go to *X.Core.Domain* under ~SolutionRoot/Source/Core/ folders in your Solution Explorer.
- Create folder under this project, named "Students" and create Student.cs in it.
- Write your student information that will save to the database. Such as: FirstName, LastName, Gender, RegisterDate etc. This is your business.

```
#sharpDox_CodeStart
using X.Core.Domain._Bases;
namespace X.Core.Domain.Students
{
    public class Student : BaseEntityWithInt, IEntity<int>
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string SchoolNumber { get; set; }
    }
}
#sharpDox_CodeEnd
```

Thank you very much and have a nice day....

**Comment by Geaz** [comment]
First of all: Please make sure, that you insert a 'tab' in front of each code line.
Furthermore there seems to be an bug with code starting right after lists.
If you use this code for example, it should work: http://paste.ubuntu.com/12243735/

**Comment by OrkanCom** [comment]
Hi Geaz, thanks for reply.

Yes, I think there is a bug with code starting right after the lists. 
When I wrote just the; "Code" before the actual codes; it fixes the view.
Thanks for support. Have a nice day...
