### ISSUE TITLE
Building Visual Studio 2015 solutions/projects fails using Console (OK with GUI)

### ISSUE THREAD

**Issue by thargy** [Geaz/sharpDox#50]
You get the following error:

    Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case
    you may be able to resolve this by installing the appropriate version of MSBuild, or the build
    may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if
    it had ToolsVersion="4.0". For more information, please see 
    http://go.microsoft.com/fwlink/?LinkId=291333. <project name>.csproj : error MSB4057:
    The target "ResolveAssemblyReferences" does not exist in the project.

**Comment by Geaz** [comment]
I tested it here with a fresh VS2015 solution. No error during build.
Could you give me some more details?

**Comment by Geaz** [comment]
If this problem occurs again, please open a new issue with some more details. Thank you very much!
