### ISSUE TITLE
Code block display with no tabulation

### ISSUE THREAD

**Issue by kadyrkulovr** [Geaz/sharpDox#54]
hello!
I am using sharpdox to generate html documentation.
How can i add tabulation in "< code ></ code >" block?

![xmldoc](https://cloud.githubusercontent.com/assets/6756259/10302985/50b586f2-6c32-11e5-8f70-5bcc9c120476.jpg)

**Comment by Geaz** [comment]
There was a small bug in the documentation parser, if you are not using the multi language feature.
I committed a fix. [Here](https://ci.appveyor.com/api/buildjobs/g2nsqnf55rv2nljt/artifacts/build.zip) you can download a compiled version.
