### ISSUE TITLE
Empty index.html

### ISSUE THREAD

**Issue by drusa** [Geaz/sharpDox#55]
After building a project i can see the following:
![image](https://cloud.githubusercontent.com/assets/18210579/15070537/12366356-1385-11e6-81e4-2897f380a689.png)
Could you help me what can cause this? Or any additional info regarding building doc.
Thanks in advance!

**Comment by Geaz** [comment]
Hi,

unfortunately, because of the nature of the html documentation, you can't open the documentation from the filesystem. Either upload it to an http server or just open a dev server on your PC. You could use for example: http://fenixwebserver.com/

Hope it helps!
