### ISSUE TITLE
Generic type parameter not displayed

### ISSUE THREAD

**Issue by arthurrump** [Geaz/sharpDox#57]
In my project I have multiple generics as return type or a parameter of a method. In the documentation is only the generic type itself visible, and not the generic type parameter:
![snip_20160513222230](https://cloud.githubusercontent.com/assets/10365257/15260807/36e54abc-1959-11e6-8b00-7b061b212f24.png)
Properties of a generic type have te same behavior: only the generic type is shown, not the parameter.
I think the generic type parameters should also been shown, as just `Dictionary` isn't very useful if you want to know what to pass to a method.

**Comment by Geaz** [comment]
This Problem should be fixed in the upcoming release. I just created a test for this scenario and it went green. Please retest on the next release in the next few days.
Thank you for the report!

**Comment by Geaz** [comment]
I just released Version 1.1! Feel free to test the new Version and tell me, if your Problem got fixed. Thank you!

**Comment by arthurrump** [comment]
Awesome! I'll test it ASAP.

**Comment by arthurrump** [comment]
It's fixed:
![snip_20160514133923](https://cloud.githubusercontent.com/assets/10365257/15268297/3d47cba6-19da-11e6-97b2-017d2e608c78.png)
Thanks!
