### ISSUE TITLE
Latest update broke <seealso>

### ISSUE THREAD

**Issue by arthurrump** [Geaz/sharpDox#58]
It looks like the <seealso> xml tag is broken in the latest update (v1.1):
![snip_20160514150529](https://cloud.githubusercontent.com/assets/10365257/15268629/b3584266-19e5-11e6-8fdf-4ce4e76ce093.png)
The amount of listed items is correct, but the links to the referenced types are not shown. In v1.0rc2 it worked correctly.

**Comment by Geaz** [comment]
Thanks for the report! This seems to be a problem linked to the roslyn refactoring. I created a test for see and seealso tags and I am working on a fix. I will provide it either this evening or tomorrow.

**Comment by Geaz** [comment]
Released new Version 1.1.1 - Problem should be fixed

**Comment by arthurrump** [comment]
It's fixed! Thanks!
