### ISSUE TITLE
Dumb Question: Where are the Exporters?

### ISSUE THREAD

**Issue by markolbert** [Geaz/sharpDox#63]
I'm confused. I cloned the repo, built the solution, and launched the GUI app. But no exporters are available. Where are they, and where do I put the plugins folder?

**Comment by Geaz** [comment]
This repo contains just the main application. Look into my other repos for the plugins or just download a prebuilt version on the homepage. 
The plugin folder goes into the main app folder. 
If you need more help, just let me know. 
Am 17.06.2016 3:30 vorm. schrieb markolbert <notifications@github.com>:I'm confused. I cloned the repo, built the solution, and launched the GUI app. But no exporters are available. Where are they, and where do I put the plugins folder?

**Comment by markolbert** [comment]
Thanx for the quick reply. I downloaded the prebuilt version, and it worked great! Although I did find out, the hard way, that it won't run from within the Program Files folder :)

A very nice project. Thanx for creating it.

**Comment by Geaz** [comment]
Ah, that is good to know - didn't knew it before :)
Will look, if I can fix this behaviour. Thanks for the information!
