### ISSUE TITLE
IndexOutOfRangeException during processing

### ISSUE THREAD

**Issue by hardly33** [Geaz/sharpDox#64]
When I try to run sharpDox on my project, I get an IndexOutOfRangeException (excuse the german stacktrace):

Starte Schritt: "Lese Projektdatei"
Starte Schritt: "Lese Code"
Die Dokumentation konnte nicht erstellt werden.
System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei SharpDox.Build.Roslyn.Parser.ProjectParser.SeeParser.ResolveAllSeeTokens()
   bei SharpDox.Build.Roslyn.RoslynParser.ResolveSeeTokens(ParserOptions parserOptions)
   bei SharpDox.Build.Roslyn.RoslynParser.GetParsedSolution(String solutionFile, ICoreConfigSection sharpDoxConfig, Dictionary`2 tokens, Boolean parseMethodCalls)
   bei SharpDox.Build.Context.Step.StructeParseCodeStep.RunStep(SDProject sdProject)
   bei SharpDox.Build.Context.BuildContext.StartBuild()

This happens after I entered all required information and press "Build", or go to "Ausgeschlossene Mitglieder" (Excluded members?) and click on the refresh button.

Unfortunately I cannot supply the project for further testing as it is not open source.

**Comment by Geaz** [comment]
Thank you for the report! Unfortunately I couldn't reproduce this error until now. But I will try further and hope I am able to come back to you with a solution.

**Comment by Geaz** [comment]
I think I found the bug. Please try the following dev build (just extract it to the old folder) and let me know, if it works.

https://ci.appveyor.com/api/buildjobs/nq26f5budfisgh5s/artifacts/build.zip

**Comment by hardly33** [comment]
Yes, with this build I don't encounter any exceptions. Thanks, great work!
