### ISSUE TITLE
Namespace descriptions not showing up

### ISSUE THREAD

**Issue by arthurrump** [Geaz/sharpDox#67]
When using the default Html exporter, namespace descriptions don't show up.

**Comment by Geaz** [comment]
Thank you for the report! There was a small bug, because of the recent change to roslyn.
Please try the following [dev build](https://ci.appveyor.com/api/buildjobs/084ryyws2bw81dpe/artifacts/build.zip) and test, if the problem is fixed. Thanks!

**Comment by arthurrump** [comment]
It's fixed! Thanks!
