### ISSUE TITLE
AppVeyor configuration as yml

### ISSUE THREAD

**Issue by BenjaminAbt** [Geaz/sharpDox#68]
Hi Gaez,

could you provide your build configuration of AppVeyor as yml-file (appveyor.yml)?
This would be easier for us to test our forks with your configuration.

**Comment by Geaz** [comment]
Hi!

Please find attached the current appveyor.yml (in a zip due to Github restrictions).

[appveyor.zip](https://github.com/Geaz/sharpDox/files/470024/appveyor.zip)

**Comment by BenjaminAbt** [comment]
Could u add this as part of your source code management? It should be placed like here. https://github.com/SchwabenCode/QuickIO
