### ISSUE TITLE
Error while trying to build

### ISSUE THREAD

**Issue by mediChlorian** [geaz/sharpDox#70]
Hi,
I've downloaded the software and startet to create a new configuration. After clicking the "Build" button I get this error messge and have no idea how to fix this problem:

Starte Schritt: "Lese Projektdatei"
Starte Schritt: "Lese Code"
Die Dokumentation konnte nicht erstellt werden.
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.IO.FileNotFoundException: Die Datei oder Assembly "System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
   bei Microsoft.Build.BackEnd.Logging.LoggingService.ProcessLoggingEvent(Object buildEvent, Boolean allowThrottling) ....

Any help would be appreciated!

sharpDox v1.2
M Frameworks 4.5.2 SDK and 4.6.2 SDK are installed

**Comment by Geaz** [comment]
Sorry for the late response! Wasn't able to reproduce this error until now. Will try a different, fresh installed machine, if I am able to reproduce the issue there.

**Comment by Geaz** [comment]
Do you have installed VS or MSBuild Tools on the machine you are running sharpDox on?

**Comment by geaz** [comment]
Closed due to inactivity...
