### ISSUE TITLE
Chrome nav bar scroll

### ISSUE THREAD

**Issue by pandazzurro** [Geaz/sharpDox#71]
Hi @Geaz, I'm looking at sharpDox website (url: http://sharpdox.de/en/doc/#!/article/home ) using Chrome browser on two different machines and the side navigation bar works with machine A and not with machine B (for example I cannot resize the side nav bar dragging its' right edge), without any error reported by the browser. OS and Chrome versions are the same on both machines (Win 10 pro and Chrome 53.0.2785.116 m (64-bit)). 
Edge and Firefox works on both machines.
Did you ever experience that before? Thanks

**Comment by Geaz** [comment]
Hi @pandazzurro, never got had this issue. Will try a few different machines, if I am able to reproduce the issue.

**Comment by pandazzurro** [comment]
The problem is Chrome on one machine.
I could not reproduce the problem.
