### ISSUE TITLE
Cannot build documentation using console

### ISSUE THREAD

**Issue by jonatan-hoff** [Geaz/sharpDox#74]
Hello,
I am trying to automatically build the documentation using the console executable. When I run this command `SharpDox.Console.exe -config test.sdox` I get the following message in the "console-log.txt" file:

`2016-11-22 13:12:50.4273 |ERROR | System.ArgumentException: Path cannot be the empty string or all whitespace.
   at System.IO.Directory.SetCurrentDirectory(String path)
   at SharpDox.Core.Config.ConfigController.Load(String fileToLoad)
   at SharpDox.Console.SDConsole.Start(String[] args)
   at SharpDox.Console.AppEntry.Main(String[] args)`

Am I doing something wrong or is there a bug here?

**Comment by Geaz** [comment]
Hello,

yes this seems to be a bug. For a workaround just use the full path to the file.

**Comment by jonatan-hoff** [comment]
Thank you for the fast response. Using absolute path solved my problem.
