### ISSUE TITLE
Disqus Not Being Loaded when Served Via SSL

### ISSUE THREAD

**Issue by kfrancis** [Geaz/sharpDox#76]
Hey,

Serving [some docs](https://ebsconnect.io/Documentation2/index.html#!/article/home) under an SSL certificate, I've had to modify the app.js to use https:// (from http://) to avoid Disqus not being shown due to the browser not loading the insecure script.

Might be useful to either use protocol-relative or to just specify the protocol somehow.

**Comment by Geaz** [comment]
Hello!

I released today a new Version which should fix this issue. Could you please check? Thank you! (New Version: https://github.com/Geaz/sharpDox/releases/download/v1.2.1/sharpDox.1.2.1.zip)
