### ISSUE TITLE
The search box is gone

### ISSUE THREAD

**Issue by mide1234** [geaz/sharpDox#80]
Hi, according to the change log the search box was added in Version 0.9.9.*. Current Version 1.2.1 seems to miss this feature. I have read the change log to see if it was removed but I have not found anything related to this feature.

I have also checked the settings if there is some option to disable or enable this feature but I have not found anything as well.

Thanks for clarifying.

**Comment by geaz** [comment]
Hello! From version 0.9 to 1.0 there was a complete rewrite of the html exporter. Unfortunately the search functionality was not implemented in the new version until now. Therefore the change log can be a bit misleading and should be changed. Sorry for this!

**Comment by mide1234** [comment]
No problem, thanks for clarifying. Do you plan to add the search functionality?

**Comment by geaz** [comment]
I don't know, if sharpDox in it current state will get the search functionality back. I am working on a sharpDox version which runs with .NET Core.
