### ISSUE TITLE
Sharpdox doesn't find the CHM compiler

### ISSUE THREAD

**Issue by Estecka** [geaz/sharpDox#97]
I have Sharpdox installed in `C:\Users\Admin\Desktop\Outils Système\Data\sharpDox 1.2.3`. I did download the chm plugin from [the site](http://sharpdox.de/en/downloads/) and placed the zip's content in the same folder.

I've tried filling the chm settings with each of these pathes, but none of them work :
`C:\Users\Admin\Desktop\Outils Système\Data\sharpDox 1.2.3\plugins`
`C:\Users\Admin\Desktop\Outils Système\Data\sharpDox 1.2.3\plugins\chm`
`C:\Users\Admin\Desktop\Outils Système\Data\sharpDox 1.2.3\plugins\chm\SharpDox.Plugins.Chm.dll`

Whichever I try, I get this error when building : 
> Could not find the chm compiler. Please set the correct path in the chm settings.
> Could not build documentation.
> SharpDox.Build.SDBuildException: There was an error with the requirements of one or more exporters. Please check the output window.
>    à SharpDox.Build.Context.Step.ExtendedCheckConfigStep.RunStep(SDProject sdProject)
>    à SharpDox.Build.Context.BuildContext.StartBuild()

**Comment by geaz** [comment]
Please install the CHM compiler: 
http://go.microsoft.com/fwlink/?LinkId=14188

And set the path to the installation directory. Should work after that.

**Comment by Estecka** [comment]
Thanks!
I had no idea the compiler was yet an entirely different thing from the plugin. Maybe put a note about it on the download page, or a readme in the plugin.

**Comment by geaz** [comment]
You are totally right about the note. I only wrote it down into the readme of the plugin repository and forgot it on the download page!
